#!/usr/bin/env ruby

if ARGV[0] && (ARGV[0] != "fix" || ARGV[1])
  system("less README.md")
else
  ENV["FIX"] = "1" if ARGV[0] == "fix"
  system("ruby extconf.rb && make && ruby repro.rb && git clean -qfX")
end
